CREATE OR REPLACE TYPE Goods_t IS TABLE OF Goods%ROWTYPE;
CREATE OR REPLACE TYPE Order_t IS TABLE OF Orders%ROWTYPE;
CREATE OR REPLACE TYPE Supply_t IS TABLE OF Supplies%ROWTYPE;
CREATE OR REPLACE TYPE Contacts IS TABLE OF Persons%ROWTYPE;

CREATE OR REPLACE TYPE Good AS OBJECT(
  ID_good INT, 
  Appel NVARCHAR2(255)
);
CREATE OR REPLACE TYPE Goods_t1 IS TABLE OF Good;

CREATE OR REPLACE TYPE Firm1 AS OBJECT(
  ID_firm INT, 
  Type_of_firm NVARCHAR2(255), 
  Appel NVARCHAR2(255)
);
CREATE OR REPLACE TYPE Firm_t1 IS TABLE OF Firm1;

CREATE OR REPLACE TYPE Firm2 AS OBJECT( 
  Type_of_firm NVARCHAR2(255), 
  Appel NVARCHAR2(255)
);
CREATE OR REPLACE TYPE Firm_t2 IS TABLE OF Firm2;