CREATE TABLE InsideAccess
(
  id_user INT PRIMARY KEY,
  Title VARCHAR2(255) NOT NULL,
  Login VARCHAR2(255) NOT NULL,
  Parole VARCHAR2(255) NOT NULL,
  Cat1 VARCHAR2(1) NOT NULL CHECK(Cat1 IN ('0','1')),
  Cat2 VARCHAR2(1) NOT NULL CHECK(Cat2 IN ('0','1')),
  Cat3 VARCHAR2(1) NOT NULL CHECK(Cat3 IN ('0','1')),
  Cat4 VARCHAR2(1) NOT NULL CHECK(Cat4 IN ('0','1')),
  Cat5 VARCHAR2(1) NOT NULL CHECK(Cat5 IN ('0','1'))
);

CREATE TABLE OutsideAccess
(
  id_user INT PRIMARY KEY,
  Title VARCHAR2(255) NOT NULL,
  Login VARCHAR2(255) NOT NULL,
  Parole VARCHAR2(255) NOT NULL
);
